// <auto-generated />
namespace BuilderTests.Data
{
    using System.Collections.Generic;

    public class Family
    {
        public long Id { get; set; }

        public string Description { get; set; }

        public List<Request> Requests { get; set; }
    }

    public class Request
    {
        public long Id { get; set; }

        public long ApproverId { get; set; }

        public long FamilyId { get; set; }
    }
}